
import { StyleSheet } from "react-native";

const COLOURS = {
  primary: "#17A1FA",
  secondary: "orange",
  tertiary: "#FF7754",
  red: "red",
  green:"green",
  gray: "#83829A",
  gray2: "#C1C0C8",
  black: "black",
  white: "#F3F4F8",
  lightWhite: "#FAFAFC",
  background: "#FFFFFF",
  buttons: "#2238A8",
};

const SIZES = {
  xSmall: 10,
  small: 12,
  medium: 16,
  large: 20,
  xLarge: 24,
  xxLarge: 32,
};

export { COLOURS, SIZES };

const borderRadius=30;
export const styles = StyleSheet.create({
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: SIZES.medium,
    width: "100%"
  },
  header: (size) => ({
    fontSize: size,
    display: "flex",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    margin: SIZES.medium,
    fontWeight: "semibold",
  }),
  text: (alignment, size, color) => ({
    color: color === null ? COLOURS.black : color,
    fontSize: size,
    textAlign: alignment,
    padding: SIZES.small,
    width: alignment!=="left" ? "80%": "auto",
    maxWidth: "80%"
  }),
  textboxes: {
    borderWidth: 2,
    borderColor: COLOURS.primary,
    borderRadius: borderRadius,
    paddingHorizontal: SIZES.large,
    paddingVertical: SIZES.medium,
    fontSize: SIZES.medium,
    letterSpacing: 0.5,
    fontWeight: "semibold",
    width: "80%",
    maxWidth: "80%",
    flexShrink: 1, // Ensures the textbox does not grow larger than its parent container
  },
  dateTextboxes: {
    borderWidth: 2,
    borderColor: COLOURS.primary,
    borderRadius: borderRadius,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    fontSize: SIZES.medium,
    letterSpacing: 0.5,
    fontWeight: "semibold",
    maxWidth: "80%",
    flexShrink: 1, // Ensures the textbox does not grow larger than its parent container
  },
  button: (color, width) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minWidth: width,
    backgroundColor: color,
    margin: SIZES.medium,
    borderColor: color,
    borderWidth: 2,
    borderRadius: borderRadius,
  }),
  smallButton: (color, width) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minWidth: width,
    backgroundColor: color,
    borderColor: COLOURS.primary,
    borderWidth: 2,
    borderRadius: borderRadius,
  }),
  profileBlank: {
    borderBottomWidth: 2,
    padding: SIZES.small,
    borderColor: COLOURS.black,
    fontSize: SIZES.medium,
    width: "80%",
  },
  fillBlank: (size) => ({
    margin: SIZES.small,
    borderBottomWidth: 2,
    padding: SIZES.small,
    borderColor: COLOURS.black,
    fontSize: size ? size : SIZES.medium,
    width: "80%",
  }),
  rowContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    width: "100%",
    marginVertical: SIZES.medium,
  },
  text_component: (color, size) => ({
    fontSize: size,
    paddingVertical: SIZES.small,
    paddingHorizontal: SIZES.medium,
    fontWeight: size > 20 ? "bold" : "normal",
    maxWidth: "80%",
  }),
  error_text: (size) => ({
    fontSize: size,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: SIZES.medium,
    color: "red",
  }),
  card: {
    display: "flex",
    alignItems: "center",
    borderColor: "white",
    justifyContent: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    marginVertical: 10,
    shadowOpacity: 0.25,
    shadowRadius: 30,
    elevation: 5,
    borderRadius: 30,
    paddingHorizontal: 30,
    paddingTop: 20,
  },
  
  button_container: (color, width) => ({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: width === null ? "100%" : width,
    backgroundColor: color,
    margin: 10,
    borderRadius: 30,
  }),
  textInput: (width) => ({
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    width: width === null ? "auto" : width,
    padding: 10,
    margin: 10,
    borderRadius: 20,
    borderColor: COLOURS.primary,
    borderWidth: 3,
  }),
  event_card: {
    display: "flex",
    margin: SIZES.small,
    padding: SIZES.small,
    justifyContent: "flex-start",
    alignContent: "center",
    backgroundColor: COLOURS.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: COLOURS.black,
  },
});
